### ISSUE TITLE
event.preventDefault

### ISSUE THREAD

**Issue by seb-jean** [stimulus-components/stimulus-password-visibility#1]
Hi,

Why event.preventDefault here: https://github.com/stimulus-components/stimulus-password-visibility/blob/327633645f7b0da4881d143d07ad0a19b6a57ad4/src/index.ts#L20

Thanks :)

**Comment by guillaumebriday** [comment]
In case the action is bind on a `<a href="#">` or on a `<button type="submit">`

I don't want the default action but only to toggle the icons.

Is it a bug in a case I didn't think about? 🤔

**Comment by seb-jean** [comment]
Ok, so we agree :).
No bug;)
