### ISSUE TITLE
Dependency to date-fns

### ISSUE THREAD

**Issue by cveneziani** [stimulus-components/stimulus-password-visibility#2]
Hello,

I see that there is a dependency to `date-fns` package.

https://github.com/stimulus-components/stimulus-password-visibility/blob/327633645f7b0da4881d143d07ad0a19b6a57ad4/package.json#L32-L34

I was wondering, is it really needed?

**Comment by guillaumebriday** [comment]
Hey 👋 

Oups not at all, it was from another package.

Just published a fix: https://github.com/stimulus-components/stimulus-password-visibility/releases/tag/v1.1.1

Thanks!
