### ISSUE TITLE
Use the `hidden` HTML attribute for toggle visibility

### ISSUE THREAD

**Issue by ocarreterom** [stimulus-components/stimulus-password-visibility#3]
The `hidden` attribute is compatible with all modern browsers https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden and at the same time it's an a11y improvement.

Also most frameworks keep in mind this attribute like [Bootstrap](https://getbootstrap.com/docs/5.1/content/reboot/#html5-hidden-attribute) or [Tailwindcss](https://github.com/tailwindlabs/tailwindcss/blob/723e8d4377eb25b66a6224f767937fa02762eb52/src/plugins/css/preflight.css#L257-L259).

**Comment by guillaumebriday** [comment]
that would be great but all other stimulus-components packages use class instead of the hidden attribute. So I think for consistency we should stick with a class for now
