### ISSUE TITLE
Disable spellcheck when displaying

### ISSUE THREAD

**Issue by olleolleolle** [stimulus-components/stimulus-password-visibility#5]
We can use [`spellcheck="false"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) on the input element when it is displaying content.

[Source](https://www.schneier.com/blog/archives/2022/09/leaking-passwords-through-the-spellchecker.html)

**Comment by guillaumebriday** [comment]
People can add it even when the password is hidden right?

**Comment by olleolleolle** [comment]
The `input type=password` seems not to support the `spellcheck` attribute, whereas the type=text does support it.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password

I was thinking that one never wants the field to have spellcheck enabled, and that this library could assist its users by helpfully disabling spellchecking when setting the type=text.

Hope this clarifies what I suggested!

**Comment by guillaumebriday** [comment]
That is a good idea!

I will add that in the documentation 👍

**Comment by guillaumebriday** [comment]
Done! Thanks @olleolleolle  🙏
