### ISSUE TITLE
Syntax for using component with stock Rails 7 application.js setup

### ISSUE THREAD

**Issue by dvodvo** [stimulus-components/stimulus-password-visibility#6]
The stimulus component affirms that the controller should read as follows
```
import { Application } from '@hotwired/stimulus'
import PasswordVisibility from 'stimulus-password-visibility'

const application = Application.start()
application.register('password-visibility', PasswordVisibility)
```
when most controllers are initialized as `import { Controller } from "@hotwired/stimulus"`

The naming of the controller is apparently agnostic to its contents, as the documentation suggests `index.js`.  The following case uses `passwordview_controller.js` 

Whatever the attempts, in the following three variants, the following errors are encountered in the browser console:  
import { Application } / Application.start()
![application_application](https://user-images.githubusercontent.com/716130/202371468-215a7e4f-6853-4c18-bf06-3c3d0c757bb1.png)

import { Controller } / Application.start()
![controller-application](https://user-images.githubusercontent.com/716130/202371740-89e8be5d-b440-4d6e-b5cc-56c85fd0cc23.png)

import { Controller } / Controller.start()
![controller controller](https://user-images.githubusercontent.com/716130/202371799-f2c4c7f5-f7fc-48b7-bac8-436f292796e8.png)

`config/importmap.rb` includes `pin "stimulus-password-visibility", to: "https://ga.jspm.io/npm:stimulus-password-visibility@2.0.0/dist/stimulus-password-visibility.es.js"`

view set to
```
<div data-controller="password-visibility">
    <input type="password" data-password-visibility-target="input" spellcheck="false" style='appearance: none; display: block; margin: 0; padding: 8px 12px 8px 48px; tab-size: 4;' />
    <button type="button" data-action="password-visibility#toggle" style='cursor: pointer; display: flex; margin: 0; padding: 0 12px 0 0; position: absolute; right: 0px; text-transform: none; top: 0px;' >
      <span data-password-visibility-target="icon"><%= fa_icon('eye', class: 'fa-1g') %></span>
      <span data-password-visibility-target="icon" class="hidden"><%= fa_icon('eye-slash', class: 'fa-1g') %></span>
    </button>
</div>
```
*do note that there is a css issue, where buttons appear below the input field, which was subject to a failed attempted to be fixed here, in an initial case, before defining a specific class for this use-case, via style definitions (tailwind is uber-view-polluting IMHO) - may require a different issue*

GIven the rails  out-of-the-box contents of `javascript/application.js`
```
import { Application } from "@hotwired/stimulus"

const application = Application.start()

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
```
how should this component be effectively written?

This is pertinent to all these components as they follow an identical pattern...

**Comment by dvodvo** [comment]
Also note that [replacing the controller with the contents of the source code](https://raw.githubusercontent.com/stimulus-components/stimulus-password-visibility/master/src/index.ts) leads to this error:
<img width="625" alt="Screen Shot 2022-11-17 at 07 46 05" src="https://user-images.githubusercontent.com/716130/202375977-2ce650a1-7d21-4e82-aa51-6098b7423dfd.png">

**Comment by guillaumebriday** [comment]
If you still have the issue, please reopen it in the main monorepo: https://github.com/stimulus-components/stimulus-components
