### ISSUE TITLE
Package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by dougc84** [stimulus-components/stimulus-password-visibility#7]
I've been working on a side project and I've used `stimulus-dropdown` without issue. It works great! So I figured I'd add `stimulus-password-visibility`. However, when I use it, I get the following message:

> Failed to resolve entry for package "stimulus-password-visibility". The package may have incorrect main/module/exports specified in its package.json.

I imported it in exactly the same way as `stimulus-dropdown` but I'm getting this message, making it unusable.

FWIW, I'm on Rails 7 (latest) and I'm using `vite_rails` instead of all the other asset builder pipelines. That shouldn't really matter though.

At a cursory glance (I haven't looked at the code), I noticed the `module` line in the `package.json` looks like:

`"module": "dist/stimulus-password-visibility.es.js"`

Whereas in `stimulus-dropdown`:

`"module": "dist/stimulus-dropdown.mjs"`

Perhaps there's a conflict with that file extension?

Here's the error message that pops up:

<img width="900" alt="Screen Shot 2023-01-19 at 1 51 18 AM" src="https://user-images.githubusercontent.com/744509/213375574-65aba56c-3ab5-4596-8cde-61d8a7ad8cb5.png">

Thanks!

**Comment by guillaumebriday** [comment]
Thanks @dougc84 🙏 

You're right, I forgot to change it! Sorry about that

Fixed in `2.1.1`

**Comment by dougc84** [comment]
@guillaumebriday Thanks!
